// backend/routes/materialsWarehouseCoatingVendor.js
// Mix's (the coating vendor's) own scoped portal -- per direct request,
// a real external login rather than internal staff tracking Mix's
// progress on their behalf. Every route here is gated by the
// materials_warehouse.coating_vendor permission AND, on top of that, a
// real data-isolation check against MatWhUserVendorAssignment: the
// caller only ever sees/touches requestNo groups whose processVendorId is
// one of their own assigned vendor(s), never another vendor's jobs, and
// never any store/project/client field -- this file's own response
// shapes simply never include those columns, rather than the frontend
// hiding them.
//
// Deliberately a separate router from materialsWarehouseOperations.js's
// internal storekeeper routes (same model, same underlying data) rather
// than adding role branches into those -- an external-facing auth
// boundary is easier to audit as its own small file than as scattered
// conditionals inside the internal one.
import express from 'express';
import { Op } from 'sequelize';
import { authenticateToken } from '../middleware/auth.js';
import { requirePermission } from '../middleware/permissions.js';
import { PERMISSIONS } from '../constants/permissions.js';
import { MatWhExternalProcessing } from '../models/MatWhExternalProcessing.js';
import { MatWhCoatingInvoice } from '../models/MatWhCoatingInvoice.js';
import { MatWhUserVendorAssignment } from '../models/MatWhUserVendorAssignment.js';
import { MatWhItem } from '../models/MatWhItem.js';

const router = express.Router();
router.use(authenticateToken, requirePermission(PERMISSIONS.MATERIALS_WAREHOUSE_COATING_VENDOR));

// Every route below needs this -- resolved once per request rather than
// per-query, since a misconfigured account (role granted before an admin
// assigned a vendor) should 403 cleanly instead of silently returning an
// empty list that reads like "no jobs yet".
//
// admin gets `null` -- a sentinel meaning "every vendor", per direct
// request ("first admin full access for it"). admin already bypasses the
// router-level requirePermission check above, so it would otherwise hit
// this portal with zero MatWhUserVendorAssignment rows of its own and
// 403 out of every route; treated as full access instead, same as the
// requirePermission bypass itself.
async function getMyVendorIds(req) {
    if (req.user.role === 'admin') return null;
    const rows = await MatWhUserVendorAssignment.findAll({ where: { userId: req.user.userId } });
    return rows.map((r) => r.vendorId);
}

function requireVendorIds(res, vendorIds) {
    if (vendorIds !== null && vendorIds.length === 0) {
        res.status(403).json({ message: 'No vendor assigned to this account yet -- contact an admin' });
        return false;
    }
    return true;
}

// Only the fields Mix should ever see -- deliberately excludes storeId,
// sourceReservationItemId/sourcePurchaseOrderItemId, isAutoGenerated,
// sentBy/receivedBy/confirmedReceivedBy (internal user ids), and any
// project/client info (this model has none of its own, but the internal
// list endpoint enriches with it from the source reservation -- this one
// never does that lookup at all).
function toVendorView(row, itemById) {
    const item = itemById.get(row.itemId);
    return {
        id: row.id,
        requestNo: row.requestNo,
        itemCode: item?.itemCode ?? null,
        itemName: item?.itemName ?? null,
        sourceColor: row.sourceColor,
        targetColor: row.targetColor,
        lengthMm: row.lengthMm,
        qtySent: row.qtySent,
        qtyReceived: row.qtyReceived,
        status: row.status,
        sentDate: row.sentDate,
        receivedDate: row.receivedDate,
        notes: row.notes,
        estimatedDeliveryDate: row.estimatedDeliveryDate,
        confirmedReceivedAt: row.confirmedReceivedAt,
        actualFinishDate: row.actualFinishDate,
    };
}

// List every job sent to this vendor -- 'draft' excluded, nothing's
// actually left the store for those yet, so there's nothing for Mix to
// have received. Frontend groups these by requestNo client-side, same
// convention as the internal ExternalProcessing.tsx list page.
router.get('/requests', async (req, res) => {
    const vendorIds = await getMyVendorIds(req);
    if (!requireVendorIds(res, vendorIds)) return;

    const where = { status: { [Op.ne]: 'draft' } };
    if (vendorIds !== null) where.processVendorId = { [Op.in]: vendorIds };
    const rows = await MatWhExternalProcessing.findAll({
        where,
        order: [['id', 'DESC']],
    });
    const itemIds = [...new Set(rows.map((r) => r.itemId))];
    const items = itemIds.length > 0 ? await MatWhItem.findAll({ where: { id: itemIds } }) : [];
    const itemById = new Map(items.map((i) => [i.id, i]));

    res.json({ items: rows.map((r) => toVendorView(r, itemById)) });
});

// Shared by every /group/:requestNo/* route below -- resolves and
// vendor-scope-checks the rows for one requestNo in one place, so an
// attempt to touch a requestNo that isn't (entirely) this vendor's own
// consistently 404s rather than leaking a partial view.
async function getMyGroupRows(req, res) {
    const vendorIds = await getMyVendorIds(req);
    if (!requireVendorIds(res, vendorIds)) return null;

    const { requestNo } = req.params;
    const rows = await MatWhExternalProcessing.findAll({
        where: { requestNo, status: { [Op.ne]: 'draft' } },
    });
    const inScope = vendorIds === null || rows.every((r) => vendorIds.includes(r.processVendorId));
    if (rows.length === 0 || !inScope) {
        res.status(404).json({ message: 'Not found' });
        return null;
    }
    return rows;
}

router.get('/group/:requestNo', async (req, res) => {
    const rows = await getMyGroupRows(req, res);
    if (!rows) return;
    const itemIds = [...new Set(rows.map((r) => r.itemId))];
    const items = itemIds.length > 0 ? await MatWhItem.findAll({ where: { id: itemIds } }) : [];
    const itemById = new Map(items.map((i) => [i.id, i]));
    res.json({ items: rows.map((r) => toVendorView(r, itemById)) });
});

// Mix confirming they physically received the batch -- same idempotent
// "only stamp confirmedReceivedAt/By once" shape as the internal route,
// just self-attributed (confirmedReceivedBy is Mix's own user id here,
// not a storekeeper's).
router.post('/group/:requestNo/confirm-received', async (req, res) => {
    const rows = await getMyGroupRows(req, res);
    if (!rows) return;

    const { notes, estimatedDeliveryDate } = req.body;
    const updates = {};
    if (!rows[0].confirmedReceivedAt) {
        updates.confirmedReceivedAt = new Date();
        updates.confirmedReceivedBy = req.user.userId;
    }
    if (notes !== undefined) updates.notes = notes || null;
    if (estimatedDeliveryDate !== undefined) updates.estimatedDeliveryDate = estimatedDeliveryDate || null;
    await MatWhExternalProcessing.update(updates, { where: { id: rows.map((r) => r.id) } });
    res.json({ items: rows.map((r) => r.id) });
});

router.post('/group/:requestNo/actual-finish', async (req, res) => {
    const rows = await getMyGroupRows(req, res);
    if (!rows) return;
    if (!rows.every((r) => r.confirmedReceivedAt)) {
        return res.status(409).json({ message: 'Confirm you received the batch before marking it finished' });
    }
    const actualFinishDate = req.body.actualFinishDate ? new Date(req.body.actualFinishDate) : new Date();
    await MatWhExternalProcessing.update({ actualFinishDate }, { where: { id: rows.map((r) => r.id) } });
    res.json({ items: rows.map((r) => r.id) });
});

router.get('/group/:requestNo/invoices', async (req, res) => {
    const rows = await getMyGroupRows(req, res);
    if (!rows) return;
    const invoices = await MatWhCoatingInvoice.findAll({
        where: { requestNo: req.params.requestNo },
        order: [['id', 'DESC']],
    });
    res.json({ items: invoices });
});

// processVendorId is deliberately taken from the job row itself, never
// from the request body -- this vendor-scope check already confirmed
// every row in the group belongs to one of the caller's own vendor ids,
// so trusting the body here would let a Mix account with two assigned
// vendors misattribute an invoice to the wrong one.
router.post('/group/:requestNo/invoices', async (req, res) => {
    const rows = await getMyGroupRows(req, res);
    if (!rows) return;

    const { vendorInvoiceNo, invDate, invDueDate, netAmt, notes, invReceivedDate } = req.body;
    if (!vendorInvoiceNo) {
        return res.status(400).json({ message: 'vendorInvoiceNo is required' });
    }
    const row = await MatWhCoatingInvoice.create({
        requestNo: req.params.requestNo,
        processVendorId: rows[0].processVendorId,
        vendorInvoiceNo,
        invDate: invDate || null,
        invDueDate: invDueDate || null,
        invReceivedDate: invReceivedDate ? new Date(invReceivedDate) : new Date(),
        netAmt: netAmt !== undefined && netAmt !== '' ? Number(netAmt) : null,
        notes: notes || null,
        enteredBy: req.user.userId,
    });
    res.status(201).json(row);
});

export default router;
