// backend/models/MatWhExternalProcessing.js
// IIT_Petra.matWhExternalProcessing -- material sent to an outside
// processor (e.g. a coating company) and received back. Modeled after
// Stock House's MIX table (§07), generalized beyond coating specifically.
// Unlike reservations, this IS a real physical movement out of and back
// into the store, so both the send and the receive-back post to
// matWhStockLedger.
import { DataTypes } from 'sequelize';
import { sequelizeUtf8 } from '../config/db.js';

export const MatWhExternalProcessing = sequelizeUtf8.define('MatWhExternalProcessing', {
    id: { type: DataTypes.INTEGER, primaryKey: true, autoIncrement: true },
    itemId: { type: DataTypes.INTEGER, allowNull: false },
    storeId: { type: DataTypes.INTEGER, allowNull: false },
    processVendorId: { type: DataTypes.INTEGER, allowNull: true },
    qtySent: { type: DataTypes.FLOAT, allowNull: false },
    qtyReceived: { type: DataTypes.FLOAT, allowNull: true },
    // Nullable -- a 'draft' job (see status below) has no send event yet.
    // Every job created through the existing manual POST /external-
    // processing route still gets a real sentDate immediately, same as
    // before this field became nullable.
    sentDate: { type: DataTypes.DATE, allowNull: true },
    receivedDate: { type: DataTypes.DATE, allowNull: true },
    // draft (auto-created from a mill-finish goods receipt, not yet a real
    // physical movement -- see routes/materialsWarehousePurchasing.js's
    // POST /goods-receipts) -> sent (storekeeper picked a vendor and
    // confirmed, POST /external-processing/:id/confirm-send -- THIS is
    // when the 'out' ledger movement actually posts) -> received. A
    // manually-created job (the existing POST /external-processing) skips
    // 'draft' entirely and starts at 'sent', unchanged from before.
    status: { type: DataTypes.STRING(20), allowNull: false, defaultValue: 'sent' }, // draft, sent, received
    sentBy: { type: DataTypes.INTEGER, allowNull: true },
    receivedBy: { type: DataTypes.INTEGER, allowNull: true },
    // What color this job is expected to come back as once coated --
    // null for an ordinary (non-coating) external-processing job. Set
    // alongside sourceReservationItemId below when auto-created.
    targetColor: { type: DataTypes.STRING(50), allowNull: true },
    // Set only on an auto-created draft job -- which reservation line it
    // exists to eventually fulfill (via the separate, explicit
    // POST /reservations/:id/items/:lineId/fulfill-shortfall action once
    // the coated stock is actually received back -- this FK alone doesn't
    // auto-apply anything).
    sourceReservationItemId: { type: DataTypes.INTEGER, allowNull: true },
    // True only for a job auto-created from a mill-finish goods receipt --
    // never for one a storekeeper started by hand through the External
    // Processing page's own "Send Out" dialog. Same convention as
    // MatWhPurchaseOrder.isAutoGenerated.
    isAutoGenerated: { type: DataTypes.BOOLEAN, allowNull: false, defaultValue: false },
}, {
    tableName: 'matWhExternalProcessing',
    timestamps: true,
});
