// backend/models/MatWhPurchaseOrder.js
// IIT_Petra.matWhPurchaseOrders -- WH.2. Status reflects that receipt and
// invoicing are independent events, not a fixed sequence (Alpha Warehouse
// Analysis report §10): draft -> sent -> confirmed -> received -> invoiced
// -> closed, but received/invoiced can happen in either order depending on
// how late the vendor's invoice arrives.
//
// internalApprovalStatus is a SEPARATE track from `status` above --
// deliberately not folded into it, since `status`'s own 'confirmed' value
// already means something else entirely (the vendor acknowledging the
// order, not an internal reviewer). Only applies to auto-generated
// shortfall POs (see MatWhReservationItem.js/services/matWhReservations.js):
// 'pending_storekeeper' (the storekeeper whose reservation line raised
// this PO confirms it has all the data it needs) -> 'pending_manager'
// (store manager confirms next) -> 'approved' (now purchasing can act on
// it same as any other PO). A manually-created PO is stamped
// 'not_required' at creation and never enters this chain at all.
import { DataTypes } from 'sequelize';
import { sequelizeUtf8 } from '../config/db.js';

export const MatWhPurchaseOrder = sequelizeUtf8.define('MatWhPurchaseOrder', {
    id: { type: DataTypes.INTEGER, primaryKey: true, autoIncrement: true },
    poNo: { type: DataTypes.STRING(50), allowNull: false, unique: true },
    // Nullable: an auto-generated PO (see services/matWhReservations.js)
    // for an item with no preferredVendorId is created with vendor left
    // unset on purpose, for someone to assign by hand -- rather than
    // blocking the reservation it came from.
    vendorId: { type: DataTypes.INTEGER, allowNull: true },
    destinationStoreId: { type: DataTypes.INTEGER, allowNull: false },
    // True only for POs raised automatically from a reservation shortfall,
    // never for one a buyer created by hand through the Purchase Orders
    // page.
    isAutoGenerated: { type: DataTypes.BOOLEAN, allowNull: false, defaultValue: false },
    // Set only on an auto-generated PO -- which reservation raised it and
    // which project that reservation was for, so a buyer opening this PO
    // doesn't have to go hunting for why it exists. projectNo/projectName
    // are copied from the reservation header at confirm time (same
    // denormalized-snapshot reasoning as MatWhReservationHeader's own
    // project fields), not live-joined.
    sourceReservationId: { type: DataTypes.INTEGER, allowNull: true },
    projectId: { type: DataTypes.INTEGER, allowNull: true },
    projectNo: { type: DataTypes.STRING(50), allowNull: true },
    projectName: { type: DataTypes.STRING(255), allowNull: true },
    notes: { type: DataTypes.STRING(500), allowNull: true },
    status: {
        type: DataTypes.STRING(20),
        allowNull: false,
        defaultValue: 'draft', // draft, sent, confirmed, received, invoiced, closed
    },
    // Set when the vendor acknowledges the order (§08's confirm step) --
    // Alpha's own live purchasing data never showed a distinct
    // acknowledgment stage, so this is new, not ported.
    orderConfirmedDate: { type: DataTypes.DATE, allowNull: true },
    isLC: { type: DataTypes.BOOLEAN, allowNull: false, defaultValue: false },
    eta: { type: DataTypes.DATEONLY, allowNull: true },
    port: { type: DataTypes.STRING(100), allowNull: true },
    shipTerms: { type: DataTypes.STRING(100), allowNull: true },
    freightExpense: { type: DataTypes.FLOAT, allowNull: true },
    netAmt: { type: DataTypes.FLOAT, allowNull: true },
    approvalDate: { type: DataTypes.DATE, allowNull: true },
    createdBy: { type: DataTypes.INTEGER, allowNull: true },
    internalApprovalStatus: {
        type: DataTypes.STRING(20),
        allowNull: false,
        defaultValue: 'not_required', // not_required, pending_storekeeper, pending_manager, approved
    },
    storekeeperConfirmedBy: { type: DataTypes.INTEGER, allowNull: true },
    storekeeperConfirmedDate: { type: DataTypes.DATE, allowNull: true },
    managerConfirmedBy: { type: DataTypes.INTEGER, allowNull: true },
    managerConfirmedDate: { type: DataTypes.DATE, allowNull: true },
}, {
    tableName: 'matWhPurchaseOrders',
    timestamps: true,
});
